# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89db7b9dffae3b9cf1eb6666b2065b001ccf4f43f70f1145480f58bbac0976dbe6fabe1147c4fb09aa8319d044231f6d8829a3e2799ab6f6f64d8d99c134dba4

test:
  secret_key_base: 54e6961705ecf331d248e700636e31b4914c82d9510389ab8a68bc97962f7c2853c88cef212dda335c9fc1f51f6451d0651c5faff5c7a4b59bb6fb7cf909621e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
